version: "3.4"

services:
    php-challenge:
        build: .
        volumes:
            - .:/var/www/php-challenge
        ports:
            - 9080:9080
        extra_hosts:
            - "host.docker.internal:host-gateway"

    db:
        image: mariadb/server:10.4
        environment:
            - MARIADB_ROOT_PASSWORD=password
            - MARIADB_DATABASE=challenge
            - MARIADB_USER=user
            - MARIADB_PASSWORD=password
        ports:
            - 4306:3306
        volumes:
            # this volume has to contain the structure and the data dumps
            # they need to be in the order they are to be applied
            # so renaming them to e.g. 2data.sql.gz and 1structure.sql.gz
            # might be necessary
            - ./.db_dumps:/docker-entrypoint-initdb.d